<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN"
  "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
<meta name="generator" content="jemdoc, see http://jemdoc.jaboc.net/" />
<meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
<link rel="icon" href="http://www-scf.usc.edu/~cbhushan/images/favicon.ico" />
<link rel="stylesheet" href="http://www-scf.usc.edu/~cbhushan/mysite.css" type="text/css" />
<title>Chitresh Bhushan</title>
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
  ga('create', 'UA-3094146-7', 'usc.edu');
  ga('send', 'pageview');
</script>
</head>
<body>
<div id="fwtitle">
<div id="toptitle">
<h1>Chitresh Bhushan</h1>
</div>
</div>
<table summary="Table for page layout." id="tlayout">
<tr valign="top">
<td id="layout-menu">
<div class="menu-item"><a href="http://www-scf.usc.edu/~cbhushan/index.html">Home</a></div>
<div class="menu-item"><a href="http://www-scf.usc.edu/~cbhushan/profile.html">Education</a></div>
<div class="menu-item"><a href="http://www-scf.usc.edu/~cbhushan/research.html">Research</a></div>
<div class="menu-category">Personal</div>
<div class="menu-item"><a href="http://www-scf.usc.edu/~cbhushan/about.html">About&nbsp;me</a></div>
<div class="menu-item"><a href="http://neuroimage.usc.edu/~chitresh/panorama.html">Panorama</a></div>
<div class="menu-item"><a href="http://www-scf.usc.edu/~cbhushan/sketch.html">Sketches</a></div>
</td>
<td id="layout-content">

<?php

// store requested url with date which generated error
$str=date("Y-m-d H:i:s") . " -- " . $_SERVER['REQUEST_URI'] . "\n";
$f = fopen('error_log.txt', 'a');
fwrite($f, $str);
fclose($f);

echo "<h1>Not Found</h1>";
echo "<p>The requested page was not found on the server: {$_SERVER['REQUEST_URI']}</p>";

?>

<p>Please use the links on the left to navigate. If you think that you are seeing this page in an error, please consider contacting me. My e-mail address can be found on <a href="http://www-scf.usc.edu/~cbhushan/index.html">Home page</a>. <br />
<br />
<br />
<br />
<br />
<br />
<br />
</p>
<div id="footer">
<div id="footer-text">
Last updated: 2014-05-08 <br/>
Page generated by <a href="http://jemdoc.jaboc.net/">jemdoc</a>.
</div>
<div id="footer-badges">
<a href="http://www.freedomain.co.nr/windows_web_hosting.php" title="ASP Web Hosting"><img src="http://murzena.imdrv.net/asp.gif" alt="ASP Web Hosting" style="width:88px;height:31px;border:0;" /></a>
</div>
</div>
</td>
</tr>
</table>
<div id="disclaimer">
</div>
<!-- Start of StatCounter Code -->
<script type="text/javascript">
var sc_project=5583967;
var sc_invisible=1;
var sc_security="96245128";
</script>
<script type="text/javascript"
src="http://www.statcounter.com/counter/counter.js"></script><noscript><div
class="statcounter"><a title="hit counter"
href="http://statcounter.com/" target="_blank"><img
class="statcounter"
src="http://c.statcounter.com/5583967/0/96245128/1/"
alt="hit counter" ></a></div></noscript>
<!-- End of StatCounter Code -->
</body>
</html>
